import Head from 'next/head';
import React from 'react';

interface Props {
  children: React.ReactNode;
}

const Layout = ({ children }: Props) => {
  return (
    <>
      <Head>
        <title>Todo App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='w-screen h-screen relative bg-gray-900 flex flex-col justify-center items-center gap-16'>
        {children}
        <footer className='flex absolute inset-0 top-auto bg-gray-800 w-full h-12 items-center justify-center text-center text-white'>
          <p>
            Made by{' '}
            <a
              className='text-gray-500 hover:underline hover:underline-offset-4'
              href='https://github.com/emorevival/nextjs-ts-todo'>
              Branko
            </a>
          </p>
        </footer>
      </div>
    </>
  );
};

export default Layout;
