import Head from 'next/head';
import React from 'react';
import Footer from './Footer';

interface Props {
  children: React.ReactNode;
}

const Layout = ({ children }: Props) => {
  return (
    <>
      <Head>
        <title>Todo App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='w-screen h-screen relative bg-gray-900 flex flex-col justify-center items-center gap-16 overflow-x-hidden'>
        {children}
        <Footer />
      </div>
    </>
  );
};

export default Layout;
